import { faker } from '@faker-js/faker';
import { ChartConfig } from '../../ui/chart';

export const chartData4 = [
  {
    year: '2009',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2010',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2011',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2012',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2013',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2014',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2015',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2016',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2017',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2018',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2019',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2020',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2021',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2022',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
  {
    year: '2023',
    Branca: faker.number.int(100),
    Preta: faker.number.int(100),
    Parda: faker.number.int(100),
    Amarela: faker.number.int(100),
    Indigena: faker.number.int(100),
    Indefinido: faker.number.int(100),
    fill: faker.color.rgb({ casing: 'upper' }),
  },
];

export const chartConfig4= {
  Branca: { label: 'Branca', color: faker.color.rgb({ casing: 'upper' }) },
  Preta: { label: 'Preta', color: faker.color.rgb({ casing: 'upper' }) },
  Parda: { label: 'Parda', color: faker.color.rgb({ casing: 'upper' }) },
  Amarela: { label: 'Amarela', color: faker.color.rgb({ casing: 'upper' }) },
  Indigena: { label: 'Indigena', color: faker.color.rgb({ casing: 'upper' }) },
  Indefinido: { label: 'Indefinido', color: faker.color.rgb({ casing: 'upper' }) },
} satisfies ChartConfig;
