import { faker } from '@faker-js/faker';
import { ChartConfig } from '../../ui/chart';

export const chartData5 = [
  {
    year: '2009',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2010',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2011',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2012',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2013',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2014',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2015',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2016',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2017',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2018',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2019',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2020',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2021',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2022',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2023',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
];

export const chartConfig5 = {
  Vestibular: { label: 'Vestibular', color: '#7CD23C' },
  Enem: { label: 'Enem', color: '#EC167C' },
  Avaliacao_Seriada: { label: 'Avaliacao_Seriada', color: '#FAB70C' },
  Selecao_Simplificada: {
    label: 'Selecao_Simplificada',
    color: '#04ACDA',
  },
  EGR: { label: 'EGR', color: '#718EC6' },
  Outro_Tipo_Selecao: { label: 'Outro_Tipo_Selecao', color: '#1A6674' },
  Processo_Seletivo: { label: 'Processo_Seletivo', color: '#890117' },
  Vaga_Remanescente: { label: 'Vaga_Remanescente', color: '#8F479B' },
  Programa_Especial: { label: 'Programa_Especial', color: '#FF8027' },
  Outra_Forma: { label: 'Outra_Forma', color: '#F30D0D' },
} satisfies ChartConfig;
