import { faker } from '@faker-js/faker';
import { ChartConfig } from '../../ui/chart';

export const chartData5 = [
  {
    year: '2009',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2010',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2011',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2012',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2013',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2014',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2015',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2016',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2017',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2018',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2019',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2020',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2021',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2022',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
  {
    year: '2023',
    Vestibular: faker.number.int(100),
    Enem: faker.number.int(100),
    Avaliação_Seriada: faker.number.int(100),
    Seleção_Simplificada: faker.number.int(100),
    EGR: faker.number.int(100),
    Outro_Tipo_Seleção: faker.number.int(100),
    Processo_Seletivo: faker.number.int(100),
    Vaga_Remanescente: faker.number.int(100),
    Programa_Especial: faker.number.int(100),
    Outra_Forma: faker.number.int(100),
  },
];

export const chartConfig5 = {
  Vestibular: { label: 'Vestibular', color: faker.color.rgb({ casing: 'upper' }) },
  Enem: { label: 'Enem', color: faker.color.rgb({ casing: 'upper' }) },
  Avaliação_Seriada: { label: 'Avaliação_Seriada', color: faker.color.rgb({ casing: 'upper' }) },
  Seleção_Simplificada: {
    label: 'Seleção_Simplificada',
    color: faker.color.rgb({ casing: 'upper' }),
  },
  EGR: { label: 'EGR', color: faker.color.rgb({ casing: 'upper' }) },
  Outro_Tipo_Seleção: { label: 'Outro_Tipo_Seleção', color: faker.color.rgb({ casing: 'upper' }) },
  Processo_Seletivo: { label: 'Processo_Seletivo', color: faker.color.rgb({ casing: 'upper' }) },
  Vaga_Remanescente: { label: 'Vaga_Remanescente', color: faker.color.rgb({ casing: 'upper' }) },
  Programa_Especial: { label: 'Programa_Especial', color: faker.color.rgb({ casing: 'upper' }) },
  Outra_Forma: { label: 'Outra_Forma', color: faker.color.rgb({ casing: 'upper' }) },
} satisfies ChartConfig;
